const mockTickets = [
    {
        uid: "TKT-001",
        createdAt: "2023-06-01T10:30:00Z",
        createdBy: "John Doe",
        issueType: "Hardware",
        currentCondition: "Not working",
        priority: "High",
        statusBadge: "Open",
        selectedEvent: "Computer won't start",
        clientNote: "My computer won't turn on when I press the power button",
        dateOfStartingWork: null,
        assignee: "Jane Smith",
        currentConditionByAdmin: null,
        problemSolvedAt: "On-site",
        actionTaken: null,
        timeTakenToSolve: null,
        relatedTickets: ["TKT-005"],
        attachments: ["screenshot.png", "error_log.txt"],
        comments: [{ author: "Jane Smith", content: "Investigating the issue", timestamp: "2023-06-01 14:30" }],
    },
    {
        uid: "TKT-002",
        createdAt: "2023-06-02T14:45:00Z",
        createdBy: "Alice Johnson",
        issueType: "Software",
        currentCondition: "Intermittent issues",
        priority: "Medium",
        statusBadge: "In Progress",
        selectedEvent: "Application Crashing",
        clientNote: "The application crashes randomly throughout the day",
        dateOfStartingWork: "2023-06-03",
        assignee: "Bob Wilson",
        currentConditionByAdmin: "Fixed",
        problemSolvedAt: "Remotely",
        actionTaken: "Updated application code",
        timeTakenToSolve: "6 hours",
        relatedTickets: ["TKT-007"],
        attachments: ["sync_log.txt"],
        comments: [
            { author: "Bob Wilson", content: "Identified the sync issue, working on a fix", timestamp: "2023-06-03 10:15" },
        ],
    },
    {
        uid: "TKT-003",
        createdAt: "2023-06-03T09:00:00Z",
        createdBy: "Emma Davis",
        issueType: "Feature Request",
        currentCondition: "Not implemented",
        priority: "Low",
        statusBadge: "Closed",
        selectedEvent: "Dark Mode",
        clientNote: "Add dark mode to the application",
        dateOfStartingWork: null,
        assignee: "Unassigned",
        currentConditionByAdmin: null,
        problemSolvedAt: null,
        actionTaken: null,
        timeTakenToSolve: null,
        relatedTickets: [],
        attachments: ["dark_mode_mockup.png"],
        comments: [],
    },
    {
        uid: "TKT-004",
        createdAt: "2023-06-04T11:15:00Z",
        createdBy: "Michael Brown",
        issueType: "Payment",
        currentCondition: "Failed",
        priority: "High",
        statusBadge: "Closed",
        selectedEvent: "Payment Failure",
        clientNote: "Users unable to complete payments",
        dateOfStartingWork: "2023-06-04",
        assignee: "Sarah Lee",
        currentConditionByAdmin: "Investigating",
        problemSolvedAt: null,
        actionTaken: null,
        timeTakenToSolve: null,
        relatedTickets: ["TKT-008"],
        attachments: ["error_screenshot.png", "transaction_log.txt"],
        comments: [
            { author: "Sarah Lee", content: "Investigating with payment gateway provider", timestamp: "2023-06-04 09:45" },
        ],
    },
    {
        uid: "TKT-005",
        createdAt: "2023-06-05T15:20:00Z",
        createdBy: "David Wilson",
        issueType: "Performance",
        currentCondition: "Improved",
        priority: "Medium",
        statusBadge: "In Progress",
        selectedEvent: "Performance Optimization",
        clientNote: "Optimize app performance on older devices",
        dateOfStartingWork: "2023-06-06",
        assignee: "Emily Clark",
        currentConditionByAdmin: "Completed",
        problemSolvedAt: "Remotely",
        actionTaken: "Optimized code and database queries",
        timeTakenToSolve: "10 hours",
        relatedTickets: ["TKT-001"],
        attachments: ["performance_report.pdf"],
        comments: [
            { author: "Emily Clark", content: "Profiling the app to identify bottlenecks", timestamp: "2023-06-06 11:20" },
        ],
    },
]

export default mockTickets;